### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'flags')

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [tsdjs/tsd#136]
Found when running tsd on https://github.com/League-of-Foundry-Developers/foundry-vtt-types/commit/6cd18412b0ab71584951d4fb1f2a08482aba495d.

```
TypeError: Cannot read properties of undefined (reading 'flags')
      at getPropertyOfObjectType (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:57213:22)
      at getPropertyOfType (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:57873:24)
      at resolveExportByName (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49087:46)
      at canHaveSyntheticDefault (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49126:21)
      at getExternalModuleMember (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49296:73)
      at getTargetOfImportSpecifier (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49374:28)
      at getTargetOfAliasDeclaration (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49443:28)
      at resolveAlias (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49483:30)
      at getSymbol (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48040:38)
      at resolveNameHelper (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48333:34)
```

<details>
<summary>Full call stack from Error.stackTraceLimit = Infinity</summary>

```
TypeError: Cannot read properties of undefined (reading 'flags')
      at getPropertyOfObjectType (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:57213:22)
      at getPropertyOfType (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:57873:24)
      at resolveExportByName (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49087:46)
      at canHaveSyntheticDefault (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49126:21)
      at getExternalModuleMember (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49296:73)
      at getTargetOfImportSpecifier (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49374:28)
      at getTargetOfAliasDeclaration (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49443:28)
      at resolveAlias (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49483:30)
      at getSymbol (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48040:38)
      at resolveNameHelper (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48333:34)
      at resolveName (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48316:20)
      at resolveEntityName (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49655:42)
      at getTargetOfExportSpecifier (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49395:17)
      at getTargetOfAliasDeclaration (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49445:28)
      at resolveAlias (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49483:30)
      at symbolIsValue (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50346:98)
      at isNamedMember (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50417:58)
      at /home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50410:21
      at Map.forEach (<anonymous>)
      at getNamedMembers (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50409:21)
      at setStructuredTypeMembers (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50433:39)
      at resolveAnonymousTypeMembers (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:56878:17)
      at resolveStructuredTypeMembers (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:57187:25)
      at getSignaturesOfStructuredType (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:57882:32)
      at resolveESModuleSymbol (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50015:36)
      at getTargetOfNamespaceImport (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49204:28)
      at getTargetOfAliasDeclaration (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49438:28)
      at resolveAlias (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49483:30)
      at getSymbol (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48040:38)
      at resolveNameHelper (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48333:34)
      at resolveName (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48316:20)
      at resolveEntityName (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49655:42)
      at getTargetOfExportSpecifier (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49395:17)
      at getTargetOfAliasDeclaration (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49445:28)
      at resolveAlias (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49483:30)
      at symbolIsValue (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50346:98)
      at isNamedMember (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50417:58)
      at /home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50410:21
      at Map.forEach (<anonymous>)
      at getNamedMembers (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50409:21)
      at setStructuredTypeMembers (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50433:39)
      at resolveAnonymousTypeMembers (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:56878:17)
      at resolveStructuredTypeMembers (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:57187:25)
      at getSignaturesOfStructuredType (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:57882:32)
      at resolveESModuleSymbol (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:50015:36)
      at getTargetOfNamespaceImport (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49204:28)
      at getTargetOfAliasDeclaration (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49438:28)
      at resolveAlias (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49483:30)
      at getSymbol (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48040:38)
      at resolveNameHelper (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48333:34)
      at resolveName (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:48316:20)
      at resolveEntityName (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49655:42)
      at getTargetOfAliasLikeExpression (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49412:29)
      at getTargetOfExportAssignment (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49401:28)
      at getTargetOfAliasDeclaration (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49448:28)
      at resolveAlias (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49483:30)
      at resolveSymbol (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49473:67)
      at resolveExternalModuleSymbol (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49965:36)
      at getTargetOfNamespaceExportDeclaration (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49388:28)
      at getTargetOfAliasDeclaration (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49450:28)
      at resolveAlias (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49483:30)
      at resolveSymbol (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:49473:67)
      at mergeSymbol (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:47826:42)
      at /home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:47941:47
      at Map.forEach (<anonymous>)
      at mergeSymbolTable (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:47939:20)
      at mergeModuleAugmentation (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:47955:17)
      at initializeTypeChecker (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:85248:25)
      at Object.createTypeChecker (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:47597:9)
      at getDiagnosticsProducingTypeChecker (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:114600:93)
      at /home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:114735:35
      at runWithCancellationToken (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:114705:24)
      at getBindAndCheckDiagnosticsForFileNoCache (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:114731:20)
      at getAndCacheDiagnostics (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:115008:26)
      at getBindAndCheckDiagnosticsForFile (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:114728:20)
      at getSemanticDiagnosticsForFile (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:114725:61)
      at /home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:114653:24
      at Object.flatMap (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:716:25)
      at getDiagnosticsHelper (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:114649:56)
      at Object.getSemanticDiagnostics (/home/josh/repos/tsd/node_modules/@tsd/typescript/typescript/lib/typescript.js:114660:20)
      at getDiagnostics (/home/josh/repos/tsd/dist/lib/compiler.js:76:10)
      at /home/josh/repos/tsd/dist/lib/index.js:91:42
      at Generator.next (<anonymous>)
      at fulfilled (/home/josh/repos/tsd/dist/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
</details>

**Comment by JoshuaKGoldberg** [comment]
This looks very similar to https://github.com/microsoft/TypeScript/issues/46587's call stack. Perhaps a `@tsd/typescript` TypeScript version bump would fix it?

**Comment by JoshuaKGoldberg** [comment]
Ah! Duplicate of https://github.com/microsoft/TypeScript/pull/47183.

**Comment by ghost91-** [comment]
@JoshuaKGoldberg https://github.com/microsoft/TypeScript/pull/47183 has been closed, but the issue still persists in tsd 0.20.0, which uses tsc 4.6.0. Is the fix in tsc already included in 4.6.0? If so, this might be something different...

**Comment by JoshuaKGoldberg** [comment]
It should be. I haven't checked this project since the 4.6.0 release.

**Comment by ghost91-** [comment]
https://github.com/League-of-Foundry-Developers/foundry-vtt-types/commit/5bc913b021df810f69c7793634aa42bdb70db5e7 is still broken :(

**Comment by ghost91-** [comment]
@SamVerschueren is there anything we can do to help solve this issue? It's a major blocker for us right now and it doesn't seem like there is any progress.

@JoshuaKGoldberg, I believe you had some ideas about what was going on...?

**Comment by ghost91-** [comment]
@SamVerschueren bump...? :)

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!

**Comment by JoshuaKGoldberg** [comment]
Oh, and: I have no idea anymore. Sorry 😄
